apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/
components:
  - ../../components/image-unstable
patches:
  - path: config-patch.yaml
    target:
      kind: ConfigMap
      name: nri-policy-validator-config